defaults: &defaults
  docker:
    - image: cimg/node:lts

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - example/node_modules
      - run: yarn test
      - persist_to_workspace:
          root: .
          paths:
            - lighttpd1.4
            - node_modules
            - pcre2
  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --access public

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-(alpha|beta)\.[0-9]+)?/
          requires:
            - test
